db:
  name: postgres
  username: ${user.name.value:postgres}
  password: 123456
  poolSize: 25

  properties:
    first: 123
    second: value
    third.value: Third
  pool:
    size: 10
    timeout: 5
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5433/dmdev_spring
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

logging:
  level:
    org.ntg: trace