db:
  name: postgres
  username: ${user.name.value:postgres}
  password: 123456
  poolSize: 25

  properties:
    first: 123
    second: value
    third.value: Third
  pool:
    size: 10
    timeout: 5
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.ntg: trace